[package]
name = "tokio-util-codec-compose"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bytes = "1"
tokio-util = { version = "0.7", features = [ "codec" ]}

[dev-dependencies]
anyhow = "1"
proptest = "1"
